### ISSUE TITLE
Add support for generic k8s cluster

### ISSUE THREAD

**Issue by larrycai** [cedrickring/kbuild#40]
It will be good to support generic k8s cluster, contents can be 

* `kubectl cp` from local to remote pod (may use [ksync](https://github.com/ksync/ksync))
* use pvc from shared local to remote pod

If needed, the remote pod (kaniko) can be run as permanent.

**Comment by cedrickring** [comment]
Hey :) I didn't think about using kbuild for dev workflows, but this might be an interesting use-case. So you're basically thinking of syncing your local files to a volume (can be any volume right?) and thus we need some mechanism to rebuild+push the image when they change. This would require some pod (not only kaniko) to run permanently in the cluster, correct.

One part I don't really get, is that a "generic k8s cluster" support would be good. As of now, I just use an empty dir volume to copy the build context to. This should work on every cluster from minikube/kind to even GKE clusters. Maybe I just got this part wrong...

**Comment by larrycai** [comment]
so far it states for GKE in readme, i thought it was not for other k8s instance. (I use rancher, it doesn't work, may raise another issue)

**Comment by cedrickring** [comment]
Sure just raise another issue. I expected it to work on every k8s cluster but I can have a look :)
